### ISSUE TITLE
Launcher crashes when clicking Application that has been downloaded by Appstore but not yet installed on device

### ISSUE THREAD

**Issue by nya-elimu** [elimu-ai/launcher#41]
![screenshot_20181215-222822](https://user-images.githubusercontent.com/15718174/50047182-29b22000-00b9-11e9-87e3-eb33b22d22d8.png)

```
2018-12-15 22:28:09.897 8167-8167/ai.elimu.launcher.debug E/HomeScreensActivity$Pla: android.content.pm.PackageManager$NameNotFoundException: ai.elimu.imagepicker
        at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:378)
        at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:360)
        at ai.elimu.launcher.HomeScreensActivity$PlaceholderFragment.initializeDialog(HomeScreensActivity.java:354)
        at ai.elimu.launcher.HomeScreensActivity$PlaceholderFragment.access$100(HomeScreensActivity.java:122)
        at ai.elimu.launcher.HomeScreensActivity$PlaceholderFragment$2.onClick(HomeScreensActivity.java:209)
```

Decide if a fix for this should be implemented in the Launcher application or in the Appstore application: https://github.com/elimu-ai/appstore

**Comment by tuancoltech** [comment]
This should have been resolved with https://github.com/elimu-ai/launcher/issues/33

**Comment by jo-elimu** [comment]
Cannot reproduce.
