### ISSUE TITLE
Bug: Release build crashes due to `java.lang.SecurityException`

### ISSUE THREAD

**Issue by nya-elimuai** [elimu-ai/launcher#49]
How to reproduce:
  1. Install Appstore (release build, version [2.3.1](https://github.com/elimu-ai/appstore/releases/tag/2.3.1))
  1. Install Launcher (release build, version [2.1.0](https://github.com/elimu-ai/launcher/releases/tag/2.1.0))

```java
2020-06-29 13:48:54.545 32338-32350/? E/DatabaseUtils: Writing exception to parcel
    java.lang.SecurityException: Permission Denial: reading ai.elimu.appstore.provider.ApplicationProvider uri content://ai.elimu.appstore.provider.application_provider/applications from pid=1340, uid=10117 requires ai.elimu.appstore.provider.READ, or grantUriPermission()
        at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:634)
        at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:503)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:214)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:102)
        at android.os.Binder.execTransact(Binder.java:731)
2020-06-29 13:48:54.550 1340-1340/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ai.elimu.launcher, PID: 1340
    java.lang.RuntimeException: Unable to start activity ComponentInfo{ai.elimu.launcher/ai.elimu.launcher.ui.HomeScreensActivity}: java.lang.SecurityException: Permission Denial: reading ai.elimu.appstore.provider.ApplicationProvider uri content://ai.elimu.appstore.provider.application_provider/applications from pid=1340, uid=10117 requires ai.elimu.appstore.provider.READ, or grantUriPermission()
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2944)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3079)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1836)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6702)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
     Caused by: java.lang.SecurityException: Permission Denial: reading ai.elimu.appstore.provider.ApplicationProvider uri content://ai.elimu.appstore.provider.application_provider/applications from pid=1340, uid=10117 requires ai.elimu.appstore.provider.READ, or grantUriPermission()
        at android.os.Parcel.createException(Parcel.java:1950)
        at android.os.Parcel.readException(Parcel.java:1918)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
        at android.content.ContentResolver.query(ContentResolver.java:802)
        at android.content.ContentResolver.query(ContentResolver.java:752)
        at android.content.ContentResolver.query(ContentResolver.java:710)
        at ai.elimu.launcher.ui.HomeScreensActivity.onCreate(HomeScreensActivity.java:97)
```

---

Related to #37

**Comment by nya-elimuai** [comment]
Can this be fixed by modifying code in the Appstore or in the Launcher itself?

**Comment by nya-elimuai** [comment]
Re-use solution implemented at https://github.com/elimu-ai/vitabu/blob/master/app/src/main/AndroidManifest.xml#L6
