### ISSUE TITLE
Resources$NotFoundException on Android 7.1.1 (API 25)

### ISSUE THREAD

**Issue by nya-elimuai** [elimu-ai/launcher#55]
Launcher crashes when pressing the "Familiar Word Reading" skill. Perhaps due to a missing launcher icon density in the [Vitabu](https://github.com/elimu-ai/vitabu) app?

```
2020-07-14 14:36:01.872 8141-8141/ai.elimu.launcher.debug I/HomeScreensActivity$Pla: initializeDialog
2020-07-14 14:36:01.883 8141-8141/ai.elimu.launcher.debug I/HomeScreensActivity$Pla: application.getPackageName(): ai.elimu.vitabu.debug
2020-07-14 14:36:01.885 8141-8141/ai.elimu.launcher.debug I/HomeScreensActivity$Pla: isTabletNavigationSkill: false
2020-07-14 14:36:01.885 8141-8141/ai.elimu.launcher.debug I/HomeScreensActivity$Pla: isLiteracySkill: true
2020-07-14 14:36:01.885 8141-8141/ai.elimu.launcher.debug I/HomeScreensActivity$Pla: isNumeracySkill: false
2020-07-14 14:36:01.885 8141-8141/ai.elimu.launcher.debug I/HomeScreensActivity$Pla: packageInfoAppstore.versionCode: 1000002
2020-07-14 14:36:01.888 8141-8141/ai.elimu.launcher.debug W/ResourceType: Failure getting entry for 0x7f0c0001 (t=11 e=1) (error -75)
2020-07-14 14:36:01.888 8141-8141/ai.elimu.launcher.debug D/AndroidRuntime: Shutting down VM
2020-07-14 14:36:01.888 8141-8141/ai.elimu.launcher.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ai.elimu.launcher.debug, PID: 8141
    android.content.res.Resources$NotFoundException: Resource ID #0x7f0c0001
        at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:199)
        at android.content.res.Resources.getDrawableForDensity(Resources.java:827)
        at ai.elimu.launcher.ui.HomeScreensActivity$PlaceholderFragment.initializeDialog(HomeScreensActivity.java:385)
        at ai.elimu.launcher.ui.HomeScreensActivity$PlaceholderFragment.access$200(HomeScreensActivity.java:153)
        at ai.elimu.launcher.ui.HomeScreensActivity$PlaceholderFragment$8.onClick(HomeScreensActivity.java:318)
        at android.view.View.performClick(View.java:5637)
        at android.view.View$PerformClick.run(View.java:22429)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

It might also be related to this commit: https://github.com/elimu-ai/launcher/commit/d51bcf1e57ca8d945ea6049201dd6878edf99181#diff-1d16b6169ab11b833cf25a577b253c49R345

**Comment by gscdev** [comment]
For Android 7.x is necessary to add ic_launcher_round.png for every dimension

**Comment by nya-elimuai** [comment]
Fixed in https://github.com/elimu-ai/vitabu/issues/13
